#!groovy

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building...'

            }
        }
        stage('Test') {
            steps {
                echo 'Testing not yet implemented.'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deployment not yet implemented.'
            }
        }
    }
}